### ISSUE TITLE
Postgresホスト先サービスの調査&決定

### ISSUE THREAD

**Issue by keitaroutakahashi** [keitaroutakahashi/marketing-app-mock#4]
## やること
- Postgresをホストするサービスの調査
  - 料金
  - 制限

＊AWS, Heroku, GCPあたり??

## 受け入れ要件
- Postgresをホストするサービスが決まっていること

**Comment by shohei1113** [comment]
- 拡張性を考えてAWS or GCP
- AWSとGCPはどちらでも良いが、k8s使用を考えるとAWSでは無料枠がないので、$300のクレジットがもらえるGCPが良い

GCPに決定
